### PR TITLE
keeping original list.js and stripping the accents from search

### PR DESCRIPTION
**Pull request by vinyll**
The main parts are:
- [custom.js](https://github.com/etalab/recherche.etalab.studio/pull/16/files#diff-e2c59e78cf79f8ab74935c5ca62a38dd)
- list.js that is the origininal minified

### CODE REVIEW

**Comment by vinyll** [comment]
Not sure why Github says "This branch cannot be rebased due to conflicts" while I resolved conflicts 🤔

**Comment by davidbgk** [comment]
You removed listjs source code?

**Comment by vinyll** [comment]
js/list….js is the origininal minified version. That's a one line.
Tha'ts why you see 1700 lines removed.

**Comment by davidbgk** [comment]
> js/list….js is the origininal minified version. That's a one line.

Ah, sometimes it's cool to go see what is going on in the code itself, that's how I barely understood how the fuzzy search works.

**Comment by davidbgk** [comment]
With that branch I don't have the same results with `election` vs `élection` (and we are loosing the accent in the query string but I don't think it's important)

**Comment by vinyll** [comment]
You're right. I was testing refreshing but as it's stripped from the url that's kind of cheating… 🎲 
I guess I should just close this and start over…

**Pull request closed without merging**
